name: Lint
on:
  push:
    paths:
      - '**.js'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc.json'
      - '.github/workflows/lint.yaml'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Check out code into the project directory
      uses: actions/checkout@v1

    - name: Install packages
      run: npm install --loglevel=verbose

    - name: Run linter
      run: npm run lint
